### ISSUE TITLE
Неправильно отображается latex в окне рисования 

### ISSUE THREAD

**Issue by abrikos110** [damoldavskiy/LexType#3]
Если вставить текст в окне рисования, то оно отображается как сырой текст, а не как готовый latex. Например, если вставить `$\int$`, то в окне рисования оно будет отображаться как '$\int$', а при компиляции как '∫'

**Comment by damoldavskiy** [comment]
На данный момент окно рисование работает с примитивами Qt. Придется встраивать какую-нибудь библиотеку, которая умеет рендерить формулы, но в ближайшее время реализовано это точно не будет.

**Comment by abrikos110** [comment]
Понятно, спасибо за ответ
