### ISSUE TITLE
Не убирается фокус

### ISSUE THREAD

**Issue by abrikos110** [damoldavskiy/LexType#5]
Иногда появляется такой баг при работе в редакторе: не получается переместить фокус на другие окна, все клавиши передаются окну редактора. Не знаю, при каких условиях он появляется. Приходится перезапускать.

**Comment by damoldavskiy** [comment]
Какая используется ОС? Перед этим используется редактор изображений, ввод текста в редакторе изображений?

**Comment by abrikos110** [comment]
Используется Ubuntu, редактор изображений не использовался, но я часто переключаюсь между окнами с помощью Alt+Tab (Super+Tab)

**Comment by damoldavskiy** [comment]
В редакторе нет специфичной обработки фокуса. Возможно, проблема в [чем-то другом](https://askubuntu.com/questions/1068030/window-focus-gets-stuck-cannot-click-outside-of-window)?

**Comment by abrikos110** [comment]
Хмм, может быть проблема не в редакторе. Может быть такая проблема с viewer? Тогда пока закрою
